build_from:
  amd64: "ghcr.io/wez/pview:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: PowerView MQTT Bridge"
  org.opencontainers.image.description: "Acts as a bridge between a Hunter Douglas PowerView Hub and Home Assistant, via the Home Assistant MQTT Integration."
  org.opencontainers.image.source: "https://github.com/wez/pview"
  org.opencontainers.image.licenses: "Apache License 2.0"