build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.18
  amd64: ghcr.io/home-assistant/amd64-base:3.18
  armhf: ghcr.io/home-assistant/armhf-base:3.18
  armv7: ghcr.io/home-assistant/armv7-base:3.18
  i386: ghcr.io/home-assistant/i386-base:3.18
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: PowerView MQTT Bridge"
  org.opencontainers.image.description: "Acts as a bridge between a Hunter Douglas PowerView Hub and Home Assistant, via the Home Assistant MQTT Integration."
  org.opencontainers.image.source: "https://github.com/wez/pview"
  org.opencontainers.image.licenses: "Apache License 2.0"
