name: PowerView to MQTT Bridge
version: "0.1.0"
slug: pview
description: >
  Acts as a bridge between a Hunter Douglas PowerView Hub and Home Assistant, via the Home Assistant MQTT Integration.
url: https://github.com/wez/pview
arch:
  - amd64
image: "ghcr.io/wez/pview:latest"
init: false
startup: services
services:
 - mqtt:need
map:
 - config:rw
options:
  mqtthost: "mqtt.localdomain"
  mqttport: 1883
schema:
  mqtthost: "str?" 
  mqttport: "int?"
  mqttuser: "str?"
  mqttpass: "str?"